version: '3.8'

services:
  api:
    image: felipefigfaria/api-python:1.0
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-python
    ports:
      - "5000:5000"
    volumes:
      - .:/app  # 🔁 Para desenvolvimento com hot reload (remova em produção)
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
